# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f1ac0f36b5624b97b7e631782d320b5893fc50fa0111d3326fd87627adabf56dbfa46cef370a2941a60254dec37dc7803883b3adf9d58003aa284cd5b09dc6

test:
  secret_key_base: f94291de5f580518143b7c93354982b2b68f014fcb882fce1ea1b783be92ece6cbb2aabebb8761ed5ea03ed76de4e1e9ef3843cc51b56635dc47e99d6ff6e43b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
